# Copyright 2014-2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Prepare Designate config
  hosts: localhost
  connection: local
  tasks:
    - name: Install OSA container environment
      copy:
        src: ../files/inventory/{{ item }}
        dest: /etc/openstack_deploy/env.d/{{ item }}
      tags: 
        - designate_setup
        - bind_setup
      with_items:
        - designate.yml
        - designate_bind.yml

    - name: Install OSA container configuration
      template:
        src: templates/designate_config.yml.j2
        dest: /etc/openstack_deploy/conf.d/designate.yml
      tags:
        - designate_setup

    - meta: refresh_inventory
    
    - name: Read user secrets file
      shell: "grep '^[a-zA-Z]' /etc/openstack_deploy/user_secrets.yml"
      register: user_secrets
      tags: 
        - designate_setup

    - name: Add missing secrets
      lineinfile:
        dest: "/etc/openstack_deploy/user_secrets.yml"
        line: "{{ item }}"
      with_items: "{{ secrets }}"
      when: user_secrets.stdout.find("{{ item }}") == -1
      register: secrets_updated
      tags: 
        - designate_setup

    - name: Update password file
      shell: "{{ oa_dir }}/scripts/pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml"
      when: secrets_updated.changed

    - name: Find existing designate_pools.yml
      stat:
        file: /etc/openstack_deploy/designate_pools.yml
      register: old_designate_pools_config

    - name: Rename designate_pools.yml to user_designate_pools.yml
      file:
        src: "{{ old_designate_pools_config.stat.path }}"
        dest: /etc/openstack_deploy/user_designate_pools.yml
      when: old_designate_pools_config.stat.exists |bool

    - name: Create user_designate_pools.yml
      template: 
        src: templates/designate_pools.yml.j2 
        dest: /etc/openstack_deploy/user_designate_pools.yml
      when: old_designate_pools_config is not defined or old_designate_pools_config is not success

- name: Setup Designate containers
  hosts: designate_all:designate_bind:os-infra_hosts
  tasks:
    - include: "{{ OA_DIR }}/playbooks/lxc-container-create.yml"

- name: Install Designate API
  hosts: localhost
  tasks:
    - name: Add designate binaries to the repo containers
      include: "{{ OA_DIR }}/playbooks/repo-install.yml"

    - name: Install Designate API services
      include: "{{ OA_DIR }}/playbooks/os-designate-install.yml"

    - name: Update haproxy services
      include: "{{ OA_DIR }}/playbooks/haproxy-install.yml"

    - name: Install BIND
      include: "setup-bind.yml"
    
    - name: Add local firewall forwarding rules
      include: "setup-infra-firewall-dns.yml"
  vars:
    secrets:
      - "designate_service_password: "
      - "designate_rabbitmq_password: "
      - "designate_galera_password: "
    oa_dir: "{{ lookup('env', 'OA_DIR') | default('/opt/openstack-ansible')}}"
